#pragma once

#define OLED_DRIVER_ENABLE
#undef USE_I2C
#undef SSD1306OLED
#define OLED_TIMEOUT 60000 // milliseconds

#define MASTER_LEFT
#define USE_SERIAL_PD2

#define SPLIT_WPM_ENABLE

#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN

#ifdef RGB_MATRIX_ENABLE
#   define RGB_MATRIX_KEYPRESSES

#   define RGB_MATRIX_MAXIMUM_BRIGHTNESS 128
#   define RGB_MATRIX_HUE_STEP 16
#   define RGB_MATRIX_SAT_STEP 32
#   define RGB_MATRIX_VAL_STEP 16
#   define RGB_MATRIX_SPD_STEP 20

#   define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_UP_DOWN
#   define RGB_MATRIX_STARTUP_HUE 255
#   define RGB_MATRIX_STARTUP_SAT 255
#   define RGB_MATRIX_STARTUP_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#   define RGB_MATRIX_STARTUP_SPD 20
#endif
